packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - "esbuild"
allowBuilds:
  '@sentry/cli': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  protobufjs: true
  workerd: true
