export {
  DEFAULT_MATCH_SETTINGS,
  GAME_CONFIG,
  GAME_DIFFICULTIES,
  GAME_DIFFICULTY_RULES,
  GAME_MODES,
  GAME_MODE_RULES,
  type GameDifficulty,
  type GameMode,
  type MatchSettings,
} from "./game/config.js";

export {
  type AnswerRegion,
  type DifferenceKind,
  type FoundMark,
  type GameEndReason,
  type GameSnapshot,
  type GameState,
  type NormalizedPoint,
  type OpponentPlayerProgress,
  type PlayerProgress,
  type PlayerResult,
  type RevealedDifference,
  type SelfPlayerProgress,
} from "./game/types.js";

export {
  GAME_PUZZLE_ASSET_MANIFEST,
  GAME_PUZZLE_IDS,
  SOLO_PUZZLE_IDS,
  type BundledPuzzleId,
  type GamePuzzleId,
  type SoloPuzzleId,
  type PuzzleAssetFileMetadata,
  type PuzzleAssetMetadata,
  type PuzzleDifficulty,
  type PuzzleRightsStatus,
} from "./puzzles/asset-manifest.js";

export {
  type ClientToServerEvents,
  type GameActionContext,
  type GameErrorPayload,
  type GuessResult,
  type MatchFoundPayload,
  type ReportReason,
  type ReportResultPayload,
  type ServerToClientEvents,
  type SessionReadyPayload,
  type SoloGuessResultPayload,
  type SoloStartedPayload,
} from "./protocol/socket-events.js";

export {
  SOLO_RULES,
  findSoloAnswer,
  guessSoloRun,
  minimumSoloHitRadius,
  soloElapsedMs,
  soloRegions,
  startSoloRun,
  type SoloGuessInput,
  type SoloGuessOutcome,
  type SoloRun,
} from "./game/solo.js";

export {
  RANKING_RULES,
  WEEKLY_RANK_REWARDS,
  koreanWeekKey,
  previousWeekKey,
  rankOf,
  rankingPayload,
  submitRecord,
  weeklyRewards,
  type RankEntry,
  type RankRow,
  type RankingPayload,
  type RankingPeriod,
  type WeeklyRewardGrant,
  type WeeklyRewardTier,
} from "./game/leaderboard.js";

export {
  DAILY_GOALS,
  PROGRESSION_RULES,
  dailyGoalFor,
  emptyGrowth,
  grantRankingReward,
  grantSoloReward,
  growthView,
  koreanDay,
  matchJourney,
  matchRewardReason,
  normalizeGrowth,
  settleMatch,
  xpForLevel,
  type DailyGoalView,
  type GrowthView,
  type PlayerStats,
  type PlayerGrowth,
  type PlayerGrowthPayload,
  type RewardReason,
  type RewardSummary,
} from "./game/progression.js";

export {
  COSMETIC_ITEMS,
  COSMETIC_ITEM_BY_ID,
  COSMETIC_SLOTS,
  DEFAULT_LOADOUT,
  buyCosmetic,
  equipCosmetic,
  normalizeLoadout,
  ownsItem,
  publicCosmetics,
  type CosmeticItem,
  type CosmeticLoadout,
  type CosmeticResult,
  type CosmeticSlot,
  type PublicCosmetics,
} from "./game/cosmetics.js";

export {
  ART_GENRES,
  ASSET_VERSION_PATTERN,
  BUNDLED_BATTLE_INFO,
  BUNDLED_SOLO_PUZZLES,
  PUZZLE_ID_PATTERN,
  bundledPuzzleCards,
  collectionKey,
  puzzleObjectKey,
  type ArtGenre,
  type CatalogPayload,
  type PuzzleCard,
  type PuzzleMode,
  type SoloAnswer,
} from "./puzzles/catalog.js";
